version: "3.8"

services:
  server:
    container_name: server-prod
    build:
      context: ./backend
      args: 
        - DEBUG=True
        - SECRET_KEY=${SECRET_KEY}
        - DB_ENGINE=${DB_ENGINE}
        - DB_NAME=${DB_NAME}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - GMAIL_API_CLIENT_ID=${GMAIL_API_CLIENT_ID}
        - GMAIL_API_CLIENT_SECRET=${GMAIL_API_CLIENT_SECRET}
        - GMAIL_API_REFRESH_TOKEN=${GMAIL_API_REFRESH_TOKEN}
        - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
        - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
        - VIEW_REDIRECT_URL=${ARG VIEW_REDIRECT_URL}
      dockerfile: Dockerfile
    image: finddiningutsc/revamp:latest-server-prod
    ports: 
      - "8000:8000"
  client:
    container_name: client-prod
    build:
      context: ./client-server
      dockerfile: Dockerfile
    image: finddiningutsc/revamp:latest-client-prod
    ports:
      - "443:443"
      - "80:80"