version: "3.8"

services:
  server:
    build:
      context: ./backend
      args: 
        - DEBUG=True
        - SECRET_KEY=${SECRET_KEY}
        - DB_ENGINE=${DB_ENGINE}
        - DB_NAME=${DB_NAME}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - GMAIL_API_CLIENT_ID=${GMAIL_API_CLIENT_ID}
        - GMAIL_API_CLIENT_SECRET=${GMAIL_API_CLIENT_SECRET}
        - GMAIL_API_REFRESH_TOKEN=${GMAIL_API_REFRESH_TOKEN}
        - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
        - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
        - VIEW_REDIRECT_URL=${VIEW_REDIRECT_URL}
        - RECAP_PRIV_KEY=${RECAP_PRIV_KEY}
        - RECAP_PUB_KEY=${RECAP_PUB_KEY}
        - GEOCODE_API_KEY=${GEOCODE_API_KEY}
        - GA_VIEW_ID=${GA_VIEW_ID}
        - GOOGLE_OAUTH2_CLIENT_EMAIL=${GOOGLE_OAUTH2_CLIENT_EMAIL}
        - GOOGLE_OAUTH2_PRIVATE_KEY=${GOOGLE_OAUTH2_PRIVATE_KEY}
        - GOOGLE_ANALYTICS_PRIVATE_KEY=${GOOGLE_ANALYTICS_PRIVATE_KEY}
        - GOOGLE_ANALYTICS_CLIENT_EMAIL=${GOOGLE_ANALYTICS_CLIENT_EMAIL}
      dockerfile: Dockerfile
    image: finddiningutsc/revamp:latest-server-test
    ports: 
      - "8000:8000"
  client:
    build:
      context: ./client-server
      dockerfile: Dockerfile
    image: finddiningutsc/revamp:latest-client-test
    ports:
      - "443:443"
      - "80:80"