# Generated by Django 2.2.20 on 2021-04-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honeypotloginattempt',
            options={'ordering': ('timestamp',), 'verbose_name': 'Malicious Login Attempt', 'verbose_name_plural': 'Malicious Login Attempts'},
        ),
    ]
