# Generated by Django 2.2.19 on 2021-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.SlugField(editable=False, max_length=512, unique=True)),
                ('image', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
