# Generated by Django 2.2.19 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210406_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='Click save to upload the image to the cloud and see the new url with image preview<br>(note that original image will be deleted if a new image is provided)', null=True, upload_to=''),
        ),
    ]
