export const cuisinesObj = [
  { item_id: 1, item_text: "Afghan" },
  { item_id: 2, item_text: "African" },
  { item_id: 3, item_text: "American" },
  { item_id: 4, item_text: "British" },
  { item_id: 5, item_text: "Canadian" },
  { item_id: 6, item_text: "Caribbean" },
  { item_id: 7, item_text: "Chinese" },
  { item_id: 8, item_text: "Ethiopian" },
  { item_id: 9, item_text: "Filipino" },
  { item_id: 10, item_text: "French" },
  { item_id: 11, item_text: "Fusion" },
  { item_id: 12, item_text: "Greek" },
  { item_id: 13, item_text: "Haitian" },
  { item_id: 14, item_text: "Indian" },
  { item_id: 15, item_text: "Indonesian" },
  { item_id: 16, item_text: "Iranian" },
  { item_id: 17, item_text: "Italian" },
  { item_id: 18, item_text: "Japanese" },
  { item_id: 19, item_text: "Korean" },
  { item_id: 20, item_text: "Lebanese" },
  { item_id: 21, item_text: "Malaysian" },
  { item_id: 22, item_text: "Mediterranean" },
  { item_id: 23, item_text: "Mexican" },
  { item_id: 24, item_text: "Moroccan" },
  { item_id: 25, item_text: "Pakistani" },
  { item_id: 26, item_text: "Polish" },
  { item_id: 27, item_text: "Singaporean" },
  { item_id: 28, item_text: "Spanish" },
  { item_id: 29, item_text: "Thai" },
  { item_id: 30, item_text: "Turkish" },
  { item_id: 31, item_text: "Vegetarian" },
  { item_id: 32, item_text: "Vietnames" },
  { item_id: 33, item_text: "West Indian" },
  { item_id: 34, item_text: "Other" },
]

export const cuisinesStr = [
  "Afghan",
  "African",
  "American",
  "British",
  "Canadian",
  "Caribbean",
  "Chinese",
  "Ethiopian",
  "Filipino",
  "French",
  "Fusion",
  "Greek",
  "Haitian",
  "Indian",
  "Indonesian",
  "Iranian",
  "Italian",
  "Japanese",
  "Korean",
  "Lebanese",
  "Malaysian",
  "Mediterranean",
  "Mexican",
  "Moroccan",
  "Pakistani",
  "Polish",
  "Singaporean",
  "Spanish",
  "Thai",
  "Turkish",
  "Vegetarian",
  "Vietnames",
  "West Indian",
  "Other",
]
