export const cuisinesObj = [
  { item_id: 1, item_text: "Afghan" },
  { item_id: 2, item_text: "American" },
  { item_id: 3, item_text: "Canadian" },
  { item_id: 4, item_text: "Chinese" },
  { item_id: 5, item_text: "Filipino" },
  { item_id: 6, item_text: "Greek" },
  { item_id: 7, item_text: "Indian" },
  { item_id: 8, item_text: "Indonesian" },
  { item_id: 9, item_text: "Iranian" },
  { item_id: 10, item_text: "Italian" },
  { item_id: 11, item_text: "Japanese" },
  { item_id: 12, item_text: "Malaysian" },
  { item_id: 13, item_text: "Mexican" },
  { item_id: 14, item_text: "Moroccan" },
  { item_id: 15, item_text: "Singaporean" },
  { item_id: 16, item_text: "Spanish" },
  { item_id: 17, item_text: "Thai" },
  { item_id: 18, item_text: "Turkish" },
  { item_id: 19, item_text: "Vegetarian" },
  { item_id: 20, item_text: "Other" },
]

export const cuisinesStr = [
  "Afghan",
  "American",
  "Canadian",
  "Chinese",
  "Filipino",
  "Greek",
  "Indian",
  "Indonesian",
  "Iranian",
  "Italian",
  "Japanese",
  "Malaysian",
  "Mexican",
  "Moroccan",
  "Singaporean",
  "Spanish",
  "Thai",
  "Turkish",
  "Vegetarian",
  "Other",
]
