export const Provinces = [
  {upper_case: "ON", lower_case: "on" },
  {upper_case: "QC", lower_case: "qc" },
  {upper_case: "AB", lower_case: "ab" },
  {upper_case: "SK", lower_case: "SK" },
  {upper_case: "BC", lower_case: "bc" },
  {upper_case: "MB", lower_case: "mb" },
  {upper_case: "NB", lower_case: "nb" },
  {upper_case: "NS", lower_case: "ns" },
  {upper_case: "PE", lower_case: "pe" },
  {upper_case: "NL", lower_case: "nl" },
  {upper_case: "YT", lower_case: "yt" },
  {upper_case: "NT", lower_case: "nt" },
  {upper_case: "NU", lower_case: "nu" },
]