export const servicesStr = [
  "Accessibility (ramps, one floor etc.)",
  "Alcohol Served",
  "Cash Only",
  "Catering",
  "Delivery",
  "Dine-In",
  "Gluten-Free Options",
  "Halal Options",
  "Live Music",
  "Meal Kits",
  "Parking",
  "Patio",
  "Pick-Up",
  "Vegan Options",
  "Vegetarian Options",
  "Wifi",
]
