# Generated by Django 2.2.19 on 2021-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
