# Generated by Django 2.2.19 on 2021-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0002_auto_20210223_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sduser',
            name='role',
            field=models.CharField(choices=[('RO', 'Restaurant Owner'), ('BU', 'Basic User')], default='BU', max_length=5),
        ),
    ]
