# Generated by Django 2.2.19 on 2021-03-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0004_sduser_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sduser',
            name='email_verified',
        ),
    ]
