# Generated by Django 2.2.19 on 2021-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0006_sduser_authid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
