# Generated by Django 2.2.19 on 2021-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0008_auto_20210312_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='default_pwd_updated',
            field=models.NullBooleanField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='sduser',
            name='pwd_update_time',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
