# Generated by Django 2.2.19 on 2021-03-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0009_auto_20210317_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sduser',
            old_name='authId',
            new_name='auth_id',
        ),
        migrations.RenameField(
            model_name='sduser',
            old_name='refreshToken',
            new_name='refresh_token',
        ),
    ]
