# Generated by Django 2.2.19 on 2021-03-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0010_auto_20210318_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='profile_id',
            field=models.IntegerField(default=None),
        ),
    ]
