# Generated by Django 2.2.19 on 2021-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0011_sduser_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='auth_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sduser',
            name='profile_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sduser',
            name='refresh_token',
            field=models.CharField(default='', max_length=1023, null=True),
        ),
    ]
