# Generated by Django 2.2.19 on 2021-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0012_auto_20210325_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='auth_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sduser',
            name='profile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sduser',
            name='pwd_update_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sduser',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
