# Generated by Django 2.2.19 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sduser', '0015_auto_20210329_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='auth_id',
            field=models.CharField(blank=True, default='', help_text='This is a unique id given by third parties (if the user logs in with a third party service)', max_length=255),
        ),
    ]
