# Generated by Django 2.2.19 on 2021-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantowner',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
