# Generated by Django 2.2.19 on 2021-03-23 15:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavRestrs',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=None)),
                ('restaurant', models.CharField(default='', max_length=24)),
            ],
        ),
    ]
