# Generated by Django 2.2.19 on 2021-03-25 19:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210324_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPost',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=24)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(max_length=4096)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
