# Generated by Django 2.2.19 on 2021-03-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurantpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrestaurant',
            name='owner_picture_url',
        ),
        migrations.RemoveField(
            model_name='pendingrestaurant',
            name='owner_story',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner_picture_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner_story',
        ),
    ]
