# Generated by Django 2.2.19 on 2021-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210329_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrestaurant',
            name='restaurant_video_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_video_desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
