# Generated by Django 2.2.19 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210330_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrestaurant',
            name='phone_ext',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_ext',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
