# Generated by Django 2.2.19 on 2021-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=50)),
                ('last_signup_time', models.DateField(blank=True, default=None)),
                ('temp_blocked', models.BooleanField(blank=True, default=False)),
                ('count_daily', models.IntegerField(blank=True, default=0)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('perm_blocked', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Signup Log',
                'verbose_name_plural': 'Signup Logs (count/ip)',
                'ordering': ['-last_signup_time'],
            },
        ),
        migrations.CreateModel(
            name='NLUser',
            fields=[
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, primary_key=True, serialize=False)),
                ('consent_status', models.CharField(choices=[('EXPRESSED', 'Expressed Consent'), ('IMPLIED', 'Implied Enquiry'), ('EXPIRED', 'Expired'), ('UNSUBSCRIBED', 'Unsubscribed')], default='IMPLIED', max_length=30)),
                ('subscribed_at', models.DateField(blank=True, default=None)),
                ('unsubscribed_at', models.DateField(blank=True, default=None)),
                ('expired_at', models.DateField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
            },
        ),
    ]
