# Generated by Django 2.2.19 on 2021-04-05 17:45

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('links', models.CharField(blank=True, max_length=1000, null=True)),
                ('visibility', models.CharField(choices=[('RO', 'Restaurant Owners Only'), ('BU', 'Consumers Only'), ('ALL', 'All')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
            },
        ),
    ]
