# Generated by Django 2.2.19 on 2021-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210405_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
