# Generated by Django 2.2.19 on 2021-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(blank=True, default=None)),
                ('postalCode', models.CharField(blank=True, default='', max_length=7)),
                ('GEO_location', models.CharField(blank=True, default='', max_length=50)),
                ('last_updated', models.DateField(auto_now=True)),
                ('consent_status', models.CharField(blank=True, choices=[('EXPRESSED', 'Expressed Consent'), ('IMPLIED', 'Implied Enquiry'), ('EXPIRED', 'Expired'), ('UNSUBSCRIBED', 'Unsubscribed')], default='IMPLIED', max_length=12)),
                ('expired_at', models.DateField(blank=True)),
                ('subscribed_at', models.DateField(blank=True)),
                ('unsubscribed_at', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'subscriber_profile',
            },
        ),
    ]
