# Generated by Django 2.2.19 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='phone_ext',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
