# Generated by Django 2.2.19 on 2021-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
