# Generated by Django 2.2.19 on 2021-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_profile', '0003_auto_20210324_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='GEO_location',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='consent_status',
            field=models.CharField(choices=[('EXPRESSED', 'Expressed Consent'), ('IMPLIED', 'Implied Enquiry'), ('EXPIRED', 'Expired'), ('UNSUBSCRIBED', 'Unsubscribed')], default='IMPLIED', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='expired_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='phone',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='postalCode',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='subscribed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='unsubscribed_at',
            field=models.DateField(null=True),
        ),
    ]
