# Generated by Django 2.2.19 on 2021-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber_profile', '0004_auto_20210325_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberprofile',
            name='GEO_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='consent_status',
            field=models.CharField(choices=[('EXPRESSED', 'Expressed Consent'), ('IMPLIED', 'Implied Enquiry'), ('EXPIRED', 'Expired'), ('UNSUBSCRIBED', 'Unsubscribed')], default='IMPLIED', max_length=12),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='postalCode',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='subscribed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberprofile',
            name='unsubscribed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
