# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      GMAIL_API_CLIENT_ID: ${{ secrets.GMAIL_API_CLIENT_ID }}
      GMAIL_API_CLIENT_SECRET: ${{ secrets.GMAIL_API_CLIENT_SECRET }}
      GMAIL_API_REFRESH_TOKEN: ${{ secrets.GMAIL_API_REFRESH_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      # Runs a set of commands using the runners shell
      - name: Create Docker imagesw
        run: |
          #login to github container
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          #build docker files and push to github container
          docker build --file ./backend/Dockerfile --tag finddiningutsc/revamp:latest-server && docker push finddiningutsc/revamp:latest-server
          docker build --file ./client-server/Dockerfile --tag finddiningutsc/revamp:latest-client && docker push finddiningutsc/revamp:latest-client
